on:
  workflow_dispatch
  
jobs:
  jekyll:
    runs-on: rpi4-test
    steps:
    - uses: actions/checkout@v2

    # Standard usage
    - uses:  helaili/jekyll-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_branch: 'gh-pages'
        
